- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - arcolinux-plank-themes-git
    - baobab
    - bitwarden
    - brasero
    - brltty
    - cheese
    - enpass-bin
    - espeak-ng
    - etcher-bin
    - flameshot-git
    - florence
    - font-manager-git
    - galculator
    - gitahead-bin
    - gitfiend
    - gitg
    - github-desktop-bin
    - gitkraken
    - gpick
    - imagewriter
    - keepassxc
    - lastpass
    - liferea
    - mcomix
    - mediainfo-gui
    - mintstick-bin
    - mintstick-git
    - mousetweaks
    - nitrogen
    - nomacs
    - onboard
    - orca
    - pdfarranger
    - plank
    - privoxy
    - screenkey-git
    - tor
    - tor-browser
    - variety
    - ventoy-bin
    - woeusb
    - xfburn
- name: "Conky"
  description: "Conky and conky collection"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - arcolinux-conky-collection-git
    - arcolinux-conky-collection-plasma-git
    - arcolinux-pipemenus-git
    - conky-lua-archers
    - yad